<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AquariumTaskbar</AssemblyName>
    <RootNamespace>AquariumTaskbar</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="icons\logo.jpg">
      <LogicalName>AquariumTaskbar.icons.logo.jpg</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
